name: Deploy Feature

on:
  delete:

env:
  ACCESS_KEY_ID: ${{ secrets.FEATURE_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.FEATURE_SECRET_ACCESS_KEY }}
  STACK_PREFIX: ${{ secrets.FEATURE_IDENTIFIER_LOWER }}
  PIPELINE_EXECUTION_ROLE: arn:aws:iam::${{secrets.FEATURE_ACCOUNT_ID}}:role/${{ secrets.FEATURE_IDENTIFIER }}PipelineExecutionRole
  CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::${{secrets.FEATURE_ACCOUNT_ID}}:role/${{ secrets.FEATURE_IDENTIFIER }}CloudFormationExecutionRole
  REGION: us-east-1

jobs:
  delete-feature:
    if: github.event.ref != 'refs/heads/master' && github.event_name == 'delete'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: aws-actions/setup-sam@v1

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: deleting-feature
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Delete feature branch stack
        env:
          FEATURE_BRANCH_NAME: ${{ github.event.ref }}
        run: |
          sam delete \
            --stack-name ${{ env.STACK_PREFIX }}-$(echo ${FEATURE_BRANCH_NAME##*/} | tr -cd '[a-zA-Z0-9-]') \
            --region ${REGION} \
            --no-prompts